/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.glass.events.KeyEvent;
import controlador.GestionFactura;
import controlador.*;
import controlador.GestionFacturasDetalle;
import controlador.GestionPersonas;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Detalle_Factura;
import modelo.FacDetalle;
import modelo.Factura;
import modelo.Persona;
import modelo.Producto;

/**
 *
 * @author Bernardo
 */
public class AnularFactura extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form ConsultaFactura
     */
    public AnularFactura() {
        
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_deta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jcedula = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledet = new javax.swing.JTable();
        jfac_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla_deta.setModel(new Tabla_Detalle_Factura());
        tabla_deta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla_deta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_detaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_deta);

        jLabel1.setText("CEDULA :");

        jcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcedulaKeyTyped(evt);
            }
        });

        tabledet.setModel(new Tabla_Detalle_Factura(new GestionFactura().getListFactura()));
        jScrollPane2.setViewportView(tabledet);

        jfac_id.setEditable(false);

        jLabel2.setText("ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcedula, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jfac_id, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfac_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_detaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_detaMouseClicked
        // TODO add your handling code here:
        
        jfac_id.setText(String.valueOf(tabla_deta.getValueAt(tabla_deta.getSelectedRow(),0 )));
        
        
        
    }//GEN-LAST:event_tabla_detaMouseClicked

    private void jcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcedulaKeyTyped
        // TODO add your handling code here:
        
         char precionar=evt.getKeyChar();
        
        if(precionar==KeyEvent.VK_ENTER){
        
           DatosCliente();
            
            //consultar.doClick();
            
             
        }
    }//GEN-LAST:event_jcedulaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void ola(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ConsultaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jcedula;
    private javax.swing.JTextField jfac_id;
    private javax.swing.JTable tabla_deta;
    private javax.swing.JTable tabledet;
    // End of variables declaration//GEN-END:variables

public boolean Error(String cedula){ //Metodo para el error
        boolean mensajes= false;
        
        ArrayList<Persona>lista =  new GestionPersonas().getListPersonas();
        for (int i = 0; i < lista.size(); i++) {
            if(lista.get(i).getPer_cedula().equals (cedula)){ 
            
                mensajes=true;
                break;
            
            }
        }
    return mensajes;
    }
    

 public boolean Existe(String id){
    
        boolean exi=false;
        ArrayList<Factura>lis=new GestionFactura().getListFacturaCliente(id);
        
        for (int i = 0; i < lis.size(); i++) {
            if(lis.get(i).getMer_per_id1()== Integer.parseInt(id)){
               exi=true;
               break;
            
            }  
            
        }
        
        
    
    return exi;
    }
 public Double Subtotal( FacDetalle fd){
        
        // precio=(double)(producto.getPro_precio());
        double subtotal=fd.getCantidad()*fd.getPrecio();
        
        
        return subtotal;
    
    
    }
    
    public Double iva(String iva,double precio){
        double ivaa=0;
        if(iva.equals("S")){
            ivaa=(precio*12)/(100);
            
        }else {
          ivaa=0;
        }
        
        return ivaa;
    };
    
    public Double Descuento(double precio,double des ){
        double descuento=0;
        
        if(des!=0){
         descuento=(precio*des)/(100);
        
    }
        
    return descuento;
    } 

    private void ConsultarDetalle() {
         ArrayList<FacDetalle>lisdes=new ArrayList<>();
        ArrayList<Detalle_Factura> lis=new GestionFacturasDetalle().getListDetalleFacturaid(Integer.parseInt(jfac_id.getText()));
        for (int i = 0; i < lis.size(); i++) {
            FacDetalle fd=new FacDetalle();
            //System.out.print(lis.get(i).getDet_catidad()+"|");
            fd.setCantidad(lis.get(i).getDet_catidad());
            fd.setPrecio(lis.get(i).getValor_unitario());
            Producto producto=new GestionProductos().getBuscarPoductoid(lis.get(i).getPro_id());
            fd.setDetalle(producto.getPro_nombre());
            
        fd.setIva(iva(producto.getPro_iva(), Subtotal(fd)));
        fd.setDescuento(Descuento(Subtotal(fd), producto.getPro_descuento()));
        double total=Subtotal(fd)-Descuento(Subtotal(fd),producto.getPro_descuento())+iva(producto.getPro_iva(), Subtotal(fd));
        fd.setSubtotal(total);
        lisdes.add(fd);
            
        }
        
        tabledet.setModel(new Tabla_Factura(lisdes));
    }

    private void DatosCliente() {
        if(Error(jcedula.getText())){
        
       Persona cli=new GestionPersonas().getBuscarCedula(jcedula.getText());
        if(Existe(String.valueOf(cli.getPer_id()))){
             ArrayList<Factura>lis=new GestionFactura().getListFacturaCliente(String.valueOf(cli.getPer_id())); 
              tabla_deta.setModel(new Tabla_Detalle_Factura(lis));
        }else{
        JOptionPane.showMessageDialog(null,"CLIENTE SIN FACTURA");
        }
        }else{
         //0107230195
         JOptionPane.showMessageDialog(null,"CLIENTE NO EXISTE");
        }
    }

}
