/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.GestionProveedores;
import Modelo.Proveedor;
import controlador.GestionFactura;
import controlador.*;
import controlador.GestionFacturasDetalle;
import controlador.GestionPersonas;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Detalle_Factura;
import modelo.FacDetalle;
import modelo.Factura;
import modelo.Persona;
import modelo.Producto;

/**
 *
 * @author Bernardo
 */
public class ConsultaCompra extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form ConsultaFactura
     */
    public ConsultaCompra() {
        
        
        initComponents();
        Llenar();
        
        //tablacom.setModel(new Tabla_Compra(new Gestion_Registro_Productos().getListCompraProducto()));
        
        
        
    }
    
     public void Llenar(){
         // TODO add your handling code here:
        for(int i=0;i< new GestionProveedores().getListProveedor().size();i++){
            provBox.addItem(new GestionProveedores().getListProveedor().get(i).getProv_nombre_empresa());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proidprov = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        provBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablacom = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        nompro = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1342, 685));
        setMinimumSize(new java.awt.Dimension(1342, 685));
        setPreferredSize(new java.awt.Dimension(1342, 685));
        getContentPane().setLayout(null);

        proidprov.setEditable(false);
        getContentPane().add(proidprov);
        proidprov.setBounds(45, 273, 42, 28);

        jLabel2.setText("ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 279, 21, 15);

        provBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provBoxActionPerformed(evt);
            }
        });
        getContentPane().add(provBox);
        provBox.setBounds(12, 328, 148, 24);

        tablacom.setModel(new Tabla_Compra(new Gestion_Registro_Productos().getListCompraProducto()));
        jScrollPane3.setViewportView(tablacom);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(218, 0, 567, 230);

        tabla2.setModel(new Tabla_Compra());
        tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(218, 313, 567, 163);

        nompro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nompro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nompro);
        nompro.setBounds(12, 389, 188, 41);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void provBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provBoxActionPerformed
        // TODO add your handling code here:
        nompro.setText("");
         Proveedor proveedor= new GestionProveedores().getBuscarProveedores((String.valueOf(provBox.getSelectedItem())));
        proidprov.setText(String.valueOf(proveedor.getProv_id()));
        
        tabla2.setModel(new Tabla_Compra(new Gestion_Registro_Productos().getListCompraProductoprov(Integer.parseInt(proidprov.getText()))));
        
        
    }//GEN-LAST:event_provBoxActionPerformed

    private void tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla2MouseClicked
        // TODO add your handling code here:
        
       // System.out.println(tabla2.getValueAt(tabla2.getSelectedRow(),3 ));
        String idx= (String.valueOf(tabla2.getValueAt(tabla2.getSelectedRow(),3 )));
        nompro.setText(new GestionProductos().getBuscarPoductoid(Integer.parseInt(idx)).getPro_nombre());
    }//GEN-LAST:event_tabla2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void ola(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ConsultaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nompro;
    private javax.swing.JTextField proidprov;
    private javax.swing.JComboBox<String> provBox;
    private javax.swing.JTable tabla2;
    private javax.swing.JTable tablacom;
    // End of variables declaration//GEN-END:variables


    
}
