/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.GestionFactura;
import controlador.*;
import controlador.GestionFacturasDetalle;
import controlador.GestionPersonas;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Detalle_Factura;
import modelo.FacDetalle;
import modelo.Factura;
import modelo.Persona;
import modelo.Producto;

/**
 *
 * @author Bernardo
 */
public class ConsultaFactura extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form ConsultaFactura
     */
    public ConsultaFactura() {
        
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_deta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jcedula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledet = new javax.swing.JTable();
        jfac_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1342, 685));
        setMinimumSize(new java.awt.Dimension(1342, 685));
        setPreferredSize(new java.awt.Dimension(1342, 685));
        getContentPane().setLayout(null);

        tabla_deta.setModel(new Tabla_Detalle_Factura());
        tabla_deta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla_deta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_detaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_deta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(224, 12, 570, 233);

        jLabel1.setText("CEDULA :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 32, 70, 27);
        getContentPane().add(jcedula);
        jcedula.setBounds(94, 32, 112, 27);

        jButton1.setText("CONSULTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(12, 98, 148, 25);

        tabledet.setModel(new Tabla_Factura());
        jScrollPane2.setViewportView(tabledet);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(224, 257, 570, 151);

        jfac_id.setEditable(false);
        getContentPane().add(jfac_id);
        jfac_id.setBounds(61, 273, 42, 28);

        jLabel2.setText("ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(22, 279, 21, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Error(jcedula.getText())){
        
       Persona cli=new GestionPersonas().getBuscarCedula(jcedula.getText());
        if(Existe(String.valueOf(cli.getPer_id()))){
             ArrayList<Factura>lis=new GestionFactura().getListFacturaCliente(String.valueOf(cli.getPer_id())); 
              tabla_deta.setModel(new Tabla_Detalle_Factura(lis));
        }else{
        JOptionPane.showMessageDialog(null,"CLIENTE SIN FACTURA");
        }
        }else{
        
         JOptionPane.showMessageDialog(null,"CLIENTE NO EXISTE");
        }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabla_detaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_detaMouseClicked
        // TODO add your handling code here:
        
        jfac_id.setText(String.valueOf(tabla_deta.getValueAt(tabla_deta.getSelectedRow(),0 )));
        
         ArrayList<FacDetalle>lisdes=new ArrayList<>();
        ArrayList<Detalle_Factura> lis=new GestionFacturasDetalle().getListDetalleFacturaid(Integer.parseInt(jfac_id.getText()));
        for (int i = 0; i < lis.size(); i++) {
            FacDetalle fd=new FacDetalle();
            //System.out.print(lis.get(i).getDet_catidad()+"|");
            fd.setCantidad(lis.get(i).getDet_catidad());
            fd.setPrecio(lis.get(i).getValor_unitario());
            Producto producto=new GestionProductos().getBuscarPoductoid(lis.get(i).getPro_id());
            fd.setDetalle(producto.getPro_nombre());
            
        fd.setIva(iva(producto.getPro_iva(), Subtotal(fd)));
        fd.setDescuento(Descuento(Subtotal(fd), producto.getPro_descuento()));
        double total=Subtotal(fd)-Descuento(Subtotal(fd),producto.getPro_descuento())+iva(producto.getPro_iva(), Subtotal(fd));
        fd.setSubtotal(total);
        lisdes.add(fd);
            
        }
        
        tabledet.setModel(new Tabla_Factura(lisdes));
        
    }//GEN-LAST:event_tabla_detaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void ola(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ConsultaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jcedula;
    private javax.swing.JTextField jfac_id;
    private javax.swing.JTable tabla_deta;
    private javax.swing.JTable tabledet;
    // End of variables declaration//GEN-END:variables

public boolean Error(String cedula){ //Metodo para el error
        boolean mensajes= false;
        
        ArrayList<Persona>lista =  new GestionPersonas().getListPersonas();
        for (int i = 0; i < lista.size(); i++) {
            if(lista.get(i).getPer_cedula().equals (cedula)){ 
            
                mensajes=true;
                break;
            
            }
        }
    return mensajes;
    }
    

 public boolean Existe(String id){
    
        boolean exi=false;
        ArrayList<Factura>lis=new GestionFactura().getListFacturaCliente(id);
        
        for (int i = 0; i < lis.size(); i++) {
            if(lis.get(i).getMer_per_id1()== Integer.parseInt(id)){
               exi=true;
               break;
            
            }  
            
        }
        
        
    
    return exi;
    }
 public Double Subtotal( FacDetalle fd){
        
        // precio=(double)(producto.getPro_precio());
        double subtotal=fd.getCantidad()*fd.getPrecio();
        
        
        return subtotal;
    
    
    }
    
    public Double iva(String iva,double precio){
        double ivaa=0;
        if(iva.equals("S")){
            ivaa=(precio*12)/(100);
            
        }else {
          ivaa=0;
        }
        
        return ivaa;
    };
    
    public Double Descuento(double precio,double des ){
        double descuento=0;
        
        if(des!=0){
         descuento=(precio*des)/(100);
        
    }
        
    return descuento;
    } 

    private void ConsultarDetalle() {
         ArrayList<FacDetalle>lisdes=new ArrayList<>();
        ArrayList<Detalle_Factura> lis=new GestionFacturasDetalle().getListDetalleFacturaid(Integer.parseInt(jfac_id.getText()));
        for (int i = 0; i < lis.size(); i++) {
            FacDetalle fd=new FacDetalle();
            //System.out.print(lis.get(i).getDet_catidad()+"|");
            fd.setCantidad(lis.get(i).getDet_catidad());
            fd.setPrecio(lis.get(i).getValor_unitario());
            Producto producto=new GestionProductos().getBuscarPoductoid(lis.get(i).getPro_id());
            fd.setDetalle(producto.getPro_nombre());
            
        fd.setIva(iva(producto.getPro_iva(), Subtotal(fd)));
        fd.setDescuento(Descuento(Subtotal(fd), producto.getPro_descuento()));
        double total=Subtotal(fd)-Descuento(Subtotal(fd),producto.getPro_descuento())+iva(producto.getPro_iva(), Subtotal(fd));
        fd.setSubtotal(total);
        lisdes.add(fd);
            
        }
        
        tabledet.setModel(new Tabla_Factura(lisdes));
    }

}
