/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import controlador.GestionFactura;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

import modelo.FacDetalle;
import modelo.Factura;

import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Bernardo
 */
public class Imprimir_Factura extends javax.swing.JFrame {
    
    JTextField email, cedula, fecha,nombre,empleado,direccion,telefono,jnumfac,sub_f,iva_f,supertotal_f;
    ArrayList<FacDetalle>tf;

    /** Creates new form Imprimir_Factura */
    public Imprimir_Factura(JTextField email,JTextField cedula,JTextField fecha,JTextField nombre,JTextField empleado,JTextField direccion,JTextField  telefono,JTextField jnumfac,ArrayList<FacDetalle>tf,JTextField sub_f,JTextField iva_f,JTextField supertotal_f) {
        initComponents();
        this.email=email;
        this.cedula=cedula;
        this.fecha=fecha;
        this.nombre=nombre;
        this.empleado=empleado;
        this.direccion=direccion;
        this.telefono=telefono;
        this.jnumfac=jnumfac;
        this.tf=tf;
        this.sub_f=sub_f;
        this.iva_f=iva_f;
        this.supertotal_f=supertotal_f;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtfac = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jdir = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtfac.setColumns(20);
        txtfac.setRows(5);
        jScrollPane1.setViewportView(txtfac);

        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(".....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jdir, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         txtfac.append("                           <<<<<SUPERMERCADO  SININCAY>>>>>"+'\n');
          txtfac.append(""+'\n');
        txtfac.append("CEDULA : "+cedula.getText()+"                            TELEFONO : "+telefono.getText() +'\n');
        txtfac.append(""+'\n');
        txtfac.append("NOMBRE : "+nombre.getText()+"                            FECHA : "+fecha.getText()+'\n');
        txtfac.append(""+'\n');
        txtfac.append("DIRECCION : "+ direccion.getText()+"                     FACTURADOR :"+ empleado.getText()+'\n');
        txtfac.append(""+'\n');
        txtfac.append("EMAIL : "+ email.getText()+'\n'); 
        txtfac.append(""+'\n');
        txtfac.append("NUMERO FACTURA : "+ jnumfac.getText()+'\n'); 
        txtfac.append(""+'\n');
        
        
        
        
       // ArrayList<Factura>lis=new GestionFactura().getListFactura();
        
        
        txtfac.append(""+'\n');
        txtfac.append("CANTIDAD   DETALLE   V.UNITARIO  IVA   DESCUENTO   TOTAL "+'\n');
         txtfac.append(""+'\n');
        for (int i = 0; i < tf.size(); i++) {
            
            txtfac.append("        "+ String.valueOf(tf.get(i).getCantidad())+"             "+ tf.get(i).getDetalle()+"          "+tf.get(i).getPrecio()+"           "+tf.get(i).getIva()+"          "+tf.get(i).getDescuento()+"           "+tf.get(i).getSubtotal()+ '\n');
            txtfac.append(""+'\n');
                    
                    
        }
        
         txtfac.append(""+'\n');
         
          txtfac.append("                                                                                                 SUBTOTAL : "+sub_f.getText()+'\n');
          txtfac.append(""+'\n');
          txtfac.append("                                                                                                 IVA      : "+iva_f.getText()+'\n');
          txtfac.append(""+'\n');
          txtfac.append("                                                                                                 TOTAL    : "+supertotal_f.getText()+'\n');
        
        try {
            FileOutputStream archivo=new FileOutputStream(jdir.getText()+".pdf");
            Document  doc =new Document();
            
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(txtfac.getText()));
            doc.close();
            
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Imprimir_Factura.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Imprimir_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null,"FACTURA GENERADA");
        
        this.setVisible(false);
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser  dig=new JFileChooser();
        int opcion =dig.showSaveDialog(this);
        
        if(opcion==JFileChooser.APPROVE_OPTION){
            
            File f= dig.getSelectedFile();
            
            jdir.setText(f.toString());
        
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jdir;
    private javax.swing.JTextArea txtfac;
    // End of variables declaration//GEN-END:variables

}
