/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.org.apache.xpath.internal.axes.SubContextList;
import controlador.Gestion;

import controlador.GestionFactura;
import controlador.GestionFacturasDetalle;
import controlador.GestionPersonas;
import controlador.GestionProductos;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Detalle_Factura;
import modelo.FacDetalle;
import modelo.Factura;
import modelo.Persona;
import modelo.Producto;

/**
 *
 * @author Bernardo
 */
public class Ventana_Factura extends javax.swing.JInternalFrame {
     
    Producto producto;
    double precio;
 
    
    Gestion gx;
     
    
    
    ArrayList<Integer>tos=new ArrayList<>();
     
    ArrayList<FacDetalle>tf=new ArrayList<>();
    Persona cliente;
    /**
     * Creates new form Ventana_Factura
     */
    public Ventana_Factura(Gestion gx) {
       
        initComponents();
        jempleado.setText(gx.getPer_nombre());
        this.gx=gx;
        llenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfactura2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        facnombrecli = new javax.swing.JTextField();
        facdireccion = new javax.swing.JTextField();
        facemial = new javax.swing.JTextField();
        factelefono = new javax.swing.JTextField();
        faccedula = new javax.swing.JTextField();
        facfecha = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jnumfac = new javax.swing.JTextField();
        sub_f = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        boxproductos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jempleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfacturax = new javax.swing.JTable();
        tcantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tcampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iva_f = new javax.swing.JTextField();
        supertotal_f = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        panelfactura2.setName("panelfactura"); // NOI18N
        panelfactura2.setLayout(null);

        jLabel6.setText("FECHA :");
        panelfactura2.add(jLabel6);
        jLabel6.setBounds(310, 90, 50, 15);

        jLabel31.setText("DIRECCION :");
        panelfactura2.add(jLabel31);
        jLabel31.setBounds(30, 100, 80, 15);

        jLabel32.setText("NOMBRE :");
        panelfactura2.add(jLabel32);
        jLabel32.setBounds(40, 60, 50, 15);

        jLabel33.setText("EMAIL :");
        panelfactura2.add(jLabel33);
        jLabel33.setBounds(40, 150, 36, 15);

        jLabel34.setText("CEDULA :");
        panelfactura2.add(jLabel34);
        jLabel34.setBounds(40, 30, 70, 15);

        jLabel35.setText("TELEFONO :");
        panelfactura2.add(jLabel35);
        jLabel35.setBounds(310, 30, 80, 15);
        panelfactura2.add(facnombrecli);
        facnombrecli.setBounds(120, 60, 150, 30);
        panelfactura2.add(facdireccion);
        facdireccion.setBounds(120, 100, 150, 30);
        panelfactura2.add(facemial);
        facemial.setBounds(120, 140, 160, 30);
        panelfactura2.add(factelefono);
        factelefono.setBounds(400, 20, 170, 30);
        panelfactura2.add(faccedula);
        faccedula.setBounds(120, 20, 170, 30);
        panelfactura2.add(facfecha);
        facfecha.setBounds(400, 80, 150, 30);

        jLabel36.setText("SUBTOTAL :");
        panelfactura2.add(jLabel36);
        jLabel36.setBounds(400, 450, 70, 15);

        jLabel37.setText("NUMERO FACTURA :");
        panelfactura2.add(jLabel37);
        jLabel37.setBounds(30, 200, 110, 15);

        jnumfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnumfacActionPerformed(evt);
            }
        });
        panelfactura2.add(jnumfac);
        jnumfac.setBounds(170, 190, 40, 30);
        panelfactura2.add(sub_f);
        sub_f.setBounds(480, 450, 90, 30);

        jButton4.setText("CONFIRMAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelfactura2.add(jButton4);
        jButton4.setBounds(630, 510, 100, 25);

        jButton13.setText("CONSULTAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panelfactura2.add(jButton13);
        jButton13.setBounds(610, 20, 120, 25);

        boxproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxproductosMouseClicked(evt);
            }
        });
        boxproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxproductosActionPerformed(evt);
            }
        });
        panelfactura2.add(boxproductos);
        boxproductos.setBounds(120, 250, 440, 24);

        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelfactura2.add(jButton1);
        jButton1.setBounds(590, 250, 120, 25);
        panelfactura2.add(jempleado);
        jempleado.setBounds(400, 140, 160, 30);

        tfacturax.setModel(new Tabla_Factura());
        jScrollPane1.setViewportView(tfacturax);

        panelfactura2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 550, 140);
        panelfactura2.add(tcantidad);
        tcantidad.setBounds(70, 250, 40, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("#");
        panelfactura2.add(jLabel1);
        jLabel1.setBounds(30, 250, 30, 30);

        jLabel2.setText("EMPLEADO :");
        panelfactura2.add(jLabel2);
        jLabel2.setBounds(320, 150, 70, 20);
        panelfactura2.add(tcampo);
        tcampo.setBounds(650, 310, 40, 30);

        jLabel3.setText(" # CAMPO :");
        panelfactura2.add(jLabel3);
        jLabel3.setBounds(590, 310, 60, 15);

        jLabel4.setText("IVA :");
        panelfactura2.add(jLabel4);
        jLabel4.setBounds(400, 480, 70, 15);

        jLabel5.setText("SUPER TOTAL :");
        panelfactura2.add(jLabel5);
        jLabel5.setBounds(380, 510, 80, 15);
        panelfactura2.add(iva_f);
        iva_f.setBounds(480, 480, 90, 30);
        panelfactura2.add(supertotal_f);
        supertotal_f.setBounds(480, 510, 90, 30);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelfactura2.add(jButton3);
        jButton3.setBounds(100, 470, 110, 25);

        jButton5.setText("CONSULTAR FACTURA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelfactura2.add(jButton5);
        jButton5.setBounds(590, 60, 160, 25);

        jButton2.setText("BORRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelfactura2.add(jButton2);
        jButton2.setBounds(610, 360, 90, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(panelfactura2, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelfactura2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public boolean Existe(String cedula){
    
        boolean exi=false;
        ArrayList<Persona>lis=new GestionPersonas().getListPersonas();
        
        for (int i = 0; i < lis.size(); i++) {
            if(lis.get(i).getPer_cedula().equals(cedula)){
               exi=true;
               break;
            
            }  
            
        }
        
        
    
    return exi;
    }
    
 /*public void Limpiarc(){ // Metodo para limpiar los jtextfield

         cliid.setText("");
        clinombre.setText("");
        clitelefono.setText("");
        clidireccion.setText("");
        clicorreo.setText("");
   }*/
      
    public boolean Error(String cedula){ //Metodo para el error
        boolean mensajes= false;
        
        ArrayList<Persona>lista =  new GestionPersonas().getListPersonas();
        for (int i = 0; i < lista.size(); i++) {
            if(lista.get(i).getPer_cedula().equals (cedula)){ 
            
                mensajes=true;
                break;
            
            }
        }
    return mensajes;
    }
    
    
   Double  TotalPagar(){
    
     double tototal=0;
        for (int i = 0; i < tf.size(); i++) {
            
            tototal=tototal+tf.get(i).getSubtotal();
        }
        
      return tototal; 
    }
    
    
    public void llenar(){
    
    
     
        for (int i = 0; i < new GestionProductos().getListProducto().size(); i++) {
            boxproductos.addItem(new GestionProductos().getListProducto().get(i).getPro_nombre());
        }
        
       
    } 
   
    
    private void jnumfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnumfacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnumfacActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       java.util.Date utilDate = new java.util.Date();
       java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        Factura fac=new Factura();
        
        //System.out.println(sqlDate);

        fac.setFact_id(codigo(getlista()));
        
        fac.setFact_codigo(codigo(getlistacod()));
        jnumfac.setText(String.valueOf(fac.getFact_codigo()));
        fac.setFact_fecha(sqlDate);
        //fac.setFact_descuento(5);
        fac.setFact_iva(Ivatotal());
        fac.setFact_subtotal(TotalPagar());
        double pag= TotalPagar()+Ivatotal();
        fac.setFact_total_pagar(pag);
        fac.setFact_estado("E");
        fac.setMer_per_id(gx.getPer_id());
        fac.setMer_per_id1(cliente.getPer_id());
        new GestionFactura().InsertaFactura(fac);
        RegistrarDetalle(fac.getFact_id());
        
        
        
        //GestionFactura fact=new GestionFactura();
       // fact.getListFactura().get(1).getFact_total_pagar();
        //GestionFacturasDetalle detalle=new GestionFacturasDetalle();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        //Borrar_tabla();
        java.util.Date utilDate = new java.util.Date();
       java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        if(Error(faccedula.getText())){

           cliente= new GestionPersonas().getBuscarCedula(faccedula.getText());
            facfecha.setText(String.valueOf((Date)sqlDate));
            facnombrecli.setText(cliente.getPer_nombre());
            factelefono.setText(cliente.getPer_telefono());

            facemial.setText(cliente.getCorreo());

            facdireccion.setText(cliente.getPer_direccion());

           

        }else{
            //Limpiarf();
            JOptionPane.showMessageDialog(null,"CLIENTE NO EXISTE");

        }

      

    }//GEN-LAST:event_jButton13ActionPerformed

    private void boxproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxproductosMouseClicked
         
        
    }//GEN-LAST:event_boxproductosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       producto=new GestionProductos().getBuscarPoductoNombre(boxproductos.getSelectedItem().toString());  
       
        
        FacDetalle det=new FacDetalle();
        
        det.setCantidad(Double.parseDouble(tcantidad.getText()));
        det.setDetalle(boxproductos.getSelectedItem().toString());
        det.setPrecio(producto.getPro_precio());
        det.setIva(iva(producto.getPro_iva(), Subtotal()));
        det.setDescuento(Descuento(Subtotal(), producto.getPro_descuento()));
        double total=Subtotal()-Descuento(Subtotal(),producto.getPro_descuento())+iva(producto.getPro_iva(), Subtotal());
        det.setSubtotal(total);
        
        tf.add(det);
        tos.add(producto.getPro_id());
        tfacturax.setModel(new Tabla_Factura(tf));
        sub_f.setText(String.valueOf(TotalPagar()));
        iva_f.setText(String.valueOf(Ivatotal()));
        supertotal_f.setText(String.valueOf(TotalPagar()+Ivatotal()));
        
        //tos.add(total);
        
        //TotalPagar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxproductosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        ///ArrayList<Detalle_Factura>lis=new GestionFacturasDetalle().getListDetalleFactura();
        
       /* for (int i = 0; i < lis.size(); i++) {
            
            System.out.print(lis.get(i).getValor_unitario()+"|");
        }*/
        
         //System.out.println(tos);
        
        Producto pro= new GestionProductos().getBuscarPoductoid(1);
        System.out.println(pro.getPro_fec_cadu()+"-"+pro.getPro_nombre());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        new ConsultaFactura().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        tf . remove ( Integer . parseInt (tcampo . getText ()));
        tos . remove ( Integer . parseInt (tcampo . getText ()));
        tfacturax . setModel ( new Tabla_Factura (tf));
         sub_f . setText ( String . valueOf (TotalPagar ()));
        iva_f . setText ( String . valueOf (Ivatotal ()));
        supertotal_f . setText ( String . valueOf (TotalPagar () + Ivatotal ()));
    }//GEN-LAST:event_jButton2ActionPerformed

   /* public Double Subtotal(){
        String cantidad=(String)tabladetalle.getValueAt(tabladetalle.getSelectedRow(), 0);
         precio=(double)(producto.getPro_precio());
        double subtotal=Double.parseDouble(cantidad)*precio;
        
        
        return subtotal;
    
    
    }*/
    public Double Subtotal(){
        Double cantidad=Double.parseDouble(tcantidad.getText());
         precio=(double)(producto.getPro_precio());
        double subtotal=cantidad*precio;
        
        
        return subtotal;
    
    
    }
    
    public Double iva(String iva,double precio){
        double ivaa=0;
        if(iva.equals("S")){
            ivaa=(precio*12)/(100);
            
        }else {
          ivaa=0;
        }
        
        return ivaa;
    };
    
    public Double Descuento(double precio, double desc ){
        double descuento=0;
        
        if(desc!=0){
         descuento=(precio*desc)/(100);
        
    }
        
    return descuento;
    } 
    /**
     * @param args the command line arguments
     */
   
    Double SumaSubtotal(){
        double sumSub=0;
        for (int i = 0; i < tf.size(); i++) {
            
            sumSub=sumSub+tf.get(i).getSubtotal();
            
        }
        
        
        return sumSub;
    
    
    
    }
    
    Double SumaIva(){
        
         double sumiva=0;
        for (int i = 0; i < tf.size(); i++) {
            
            sumiva=sumiva+tf.get(i).getIva();
            
        }
        return sumiva;
    
    
    
    }
    
    
    Double SumaDescuento(){
        
         double sumdes=0;
        for (int i = 0; i < tf.size(); i++) {
            
            sumdes=sumdes+tf.get(i).getDescuento();
            
        }
        return sumdes;
    
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxproductos;
    private javax.swing.JTextField faccedula;
    private javax.swing.JTextField facdireccion;
    private javax.swing.JTextField facemial;
    private javax.swing.JTextField facfecha;
    private javax.swing.JTextField facnombrecli;
    private javax.swing.JTextField factelefono;
    private javax.swing.JTextField iva_f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jempleado;
    private javax.swing.JTextField jnumfac;
    private javax.swing.JPanel panelfactura2;
    private javax.swing.JTextField sub_f;
    private javax.swing.JTextField supertotal_f;
    private javax.swing.JTextField tcampo;
    private javax.swing.JTextField tcantidad;
    private javax.swing.JTable tfacturax;
    // End of variables declaration//GEN-END:variables

    private Double Ivatotal() {
        
       
        double total=((Double.parseDouble(sub_f.getText()))*(12))/(100);
        
        
        return total;
        
    }
    
    public int  codigo(ArrayList<Integer>lis){
      boolean n=false;
      int num=1;
        while (n==false) {      
             num=new Random().nextInt(100)+0;
            if(!new GestionFactura().comparar(num, lis)){
               n=true;
            
            }
        }

      return num;
     }
    
     public  ArrayList<Integer>getlista(){
        ArrayList<Integer>list=new ArrayList<>();
        ArrayList<Factura>list1=new GestionFactura().getListFactura();
        for (int i = 0; i < list1.size(); i++) {
            list.add(list1.get(i).getFact_id());                                                                                                                                                
        }
    return list;
    }
     
     
    public  ArrayList<Integer>getlistacod(){
        ArrayList<Integer>list=new ArrayList<>();
        ArrayList<Factura>list1=new GestionFactura().getListFactura();
        for (int i = 0; i < list1.size(); i++) {
            list.add(list1.get(i).getFact_codigo());                                                                                                                                                
        }
    return list;
    }
    
    public  ArrayList<Integer>getlistaiddet(){
        ArrayList<Integer>list=new ArrayList<>();
        ArrayList<Detalle_Factura>list1=new GestionFacturasDetalle().getListDetalleFactura();
        for (int i = 0; i < list1.size(); i++) {
            list.add(list1.get(i).getDet_id());                                                                                                                                                
        }
    return list;
    }

    private void RegistrarDetalle(int idfac) {
        
        for (int i = 0; i <tf.size(); i++) {
            Detalle_Factura df=new Detalle_Factura();
            df.setDet_id(codigo(getlistaiddet()));
            df.setDet_catidad(tf.get(i).getCantidad());
            df.setValor_unitario(tf.get(i).getPrecio());
            df.setPro_id(tos.get(i));
            df.setFac_id(idfac);
            new GestionFacturasDetalle().InsertaFacturaDetalle(df);
            int can=(int) tf.get(i).getCantidad();
            Producto pro= new GestionFacturasDetalle().ActualizarStock(can,tos.get(i) );
            //System.out.println(pro.getPro_nombre()+"-"+pro.getPro_stock());
            new GestionProductos().ActualizarProducto(pro);
            
            
        }
        
        
    }
    
}
