/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Gestion;

import controlador.GestionPersonas;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Persona;

/**
 *
 * @author Bernardo
 */
public class Vent_Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vent_Clientes
     */
    public Vent_Clientes() {
        initComponents();
        setClosable(true);
        setDefaultLocale(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jced = new javax.swing.JTextField();
        jnom = new javax.swing.JTextField();
        jape = new javax.swing.JTextField();
        jtel = new javax.swing.JTextField();
        jcar = new javax.swing.JTextField();
        jdir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jusu = new javax.swing.JTextField();
        jcont = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lcod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jeda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jcorr = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setAlignmentX(0.2F);
        setAlignmentY(0.2F);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CEDULA :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, 58, 46));

        jLabel2.setText("NOMBRE :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, 58, 23));

        jLabel3.setText("APELLIDO :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 185, 58, 23));

        jLabel4.setText("USUARIO :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 364, 67, 23));

        jLabel5.setText("TELEFONO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 479, 58, 23));

        jLabel6.setText("CARGO : ");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 285, -1, -1));

        jced.setAlignmentX(0.2F);
        jced.setAlignmentY(0.2F);
        getContentPane().add(jced, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 99, 119, -1));

        jnom.setAlignmentX(0.2F);
        jnom.setAlignmentY(0.2F);
        getContentPane().add(jnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 145, 119, -1));

        jape.setAlignmentX(0.2F);
        jape.setAlignmentY(0.2F);
        getContentPane().add(jape, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 187, 119, -1));

        jtel.setAlignmentX(0.2F);
        jtel.setAlignmentY(0.2F);
        getContentPane().add(jtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 481, 128, -1));

        jcar.setAlignmentX(0.2F);
        jcar.setAlignmentY(0.2F);
        getContentPane().add(jcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 130, -1));

        jdir.setAlignmentX(0.2F);
        jdir.setAlignmentY(0.2F);
        getContentPane().add(jdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 439, 128, -1));

        tabla.setModel(new Tabla_Clientes());
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 25, 827, -1));

        jButton1.setText("ACTUALIZAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 478, -1, -1));

        jButton2.setText("BUSCAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 478, -1, -1));

        jButton3.setText("REGISTRAR");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 478, -1, -1));

        jButton4.setText("ELIMINAR");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1051, 478, -1, -1));

        jLabel7.setText("CONTRASEÑA :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 405, 67, 23));

        jLabel8.setText("DIRECCION :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 437, 67, 23));
        getContentPane().add(jusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 366, 123, -1));
        getContentPane().add(jcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 407, 123, -1));

        jButton5.setText("lLISTAR");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 478, -1, -1));

        jLabel9.setText("CODIGO :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, -1, -1));

        lcod.setEditable(false);
        getContentPane().add(lcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 54, 38, -1));

        jLabel10.setText("EDAD :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 228, -1, -1));

        jeda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jedaMouseClicked(evt);
            }
        });
        getContentPane().add(jeda, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 226, 119, -1));

        jLabel11.setText("CORREO :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 329, -1, -1));
        getContentPane().add(jcorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 327, 128, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public int  codigo(ArrayList<Integer>lis){
      boolean n=false;
      int num=1;
        while (n==false) {      
             num=new Random().nextInt(100)+0;
            if(!new GestionPersonas().comparar(num, lis)){
               n=true;
            
            }
        }

      return num;
     }
    
    public  ArrayList<Integer>getlista(){
        ArrayList<Integer>list=new ArrayList<>();
        ArrayList<Persona>list1=new GestionPersonas().getListPersonas();
        for (int i = 0; i < list1.size(); i++) {
            list.add(list1.get(i).getPer_id());
        }
    return list;
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Persona per=new Persona();
       
         
         
        if(new Gestion().Cedula(jced.getText()) && jced.getText().length()==10){
            
        if(!Existe(jced.getText())){
        per.setPer_id(codigo(getlista()));
        per.setPer_cedula(jced.getText());
        per.setPer_nombre(jnom.getText());
        per.setPer_apellido(jape.getText());
        per.setPer_direccion(jdir.getText());
        per.setPer_telefono(jtel.getText());
        per.setPer_edad(0);
       
        per.setEmp_cargo("N");
        per.setEmp_contrasena("null");
        per.setEmp_usuario("null");
        per.setCorreo(jcorr.getText());
        new GestionPersonas().InsertPersona(per);
         JOptionPane.showMessageDialog(null,"REGISTRO CORRECTO");
        
        }  else{
        JOptionPane.showMessageDialog(null,"PERSONA YA REGISTRADA");
        }  
            
        }else {
        
            JOptionPane.showMessageDialog(null,"CEDULA INCORRECTA");
        }
       
       
      
        
        
        
       
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ArrayList<Persona>liscli=new ArrayList<>();
        ArrayList<Persona>listotal=new GestionPersonas().getListPersonas();
        
        for (int i = 0; i < listotal.size(); i++) {
            
            if(listotal.get(i).getEmp_cargo().equals("N")){
                liscli.add(listotal.get(i));
            
            }
        }
        
       tabla.setModel(new Tabla_Empleados(liscli));
       
       // System.out.println(new GestionPersonas().getBuscarCliente("1").getPer_id());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //System.out.println(codigo(getlista()));
        if(Existe(jced.getText())){
        Persona per=new GestionPersonas().getBuscarCedula(jced.getText());
        
        lcod.setText(String.valueOf(per.getPer_id()));
        jced.setText(per.getPer_cedula());
        jnom.setText(per.getPer_nombre());
        jape.setText(per.getPer_apellido());
        //jcar.setText(per.getEmp_cargo());
       // jusu.setText(per.getEmp_usuario());
       // jcont.setText(per.getEmp_contrasena());
        jdir.setText(per.getPer_direccion());
        jtel.setText(per.getPer_telefono());
        jcorr.setText(per.getCorreo());
        } else {
                
                JOptionPane.showMessageDialog(null,"PERSONA NO EXISTE");
          }
        
        //jeda.setText(String.valueOf(per.getPer_edad()));
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        //jnom.setText((String) tabla.getValueAt(tabla.getSelectedRow(), tabla.getSelectedColumn()));
        lcod.setText(String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 0)));
        jced.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 1));
        jnom.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 2));
        jape.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 3));
        jcorr.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 4));
        jcar.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 5));
        jusu.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 6));
        jcont.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 7));
        jdir.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 8));
        jtel.setText((String) tabla.getValueAt(tabla.getSelectedRow(), 9));
        jeda.setText(String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 10)));
        //lcod1.setText(String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 10)));
    
       
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Persona per=new Persona();
        
        per.setPer_id(Integer.parseInt(lcod.getText()));
        per.setPer_cedula(jced.getText());
        per.setPer_nombre(jnom.getText());
        per.setPer_apellido(jape.getText());
        per.setPer_direccion(jdir.getText());
        per.setPer_telefono(jtel.getText());
         per.setPer_edad(0);
        //per.setPer_edad(Integer.parseInt(jeda.getText()));
       /* per.setEmp_cargo(jcar.getText());
        per.setEmp_contrasena(jcont.getText());
        per.setEmp_usuario(jusu.getText());*/
        per.setCorreo(jcorr.getText());
       per.setEmp_cargo("N");
        per.setEmp_contrasena("null");
        per.setEmp_usuario("null");
        
        
        
        
        new GestionPersonas().ActualizarPersona(per);
        JOptionPane.showMessageDialog(null,"ACTUALIZACION CORRECTO");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
        new GestionPersonas().EliminarPersona(jced.getText());
        JOptionPane.showMessageDialog(null,"ELIMINACION CORRECTA");
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jedaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jedaMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jape;
    private javax.swing.JTextField jcar;
    private javax.swing.JTextField jced;
    private javax.swing.JTextField jcont;
    private javax.swing.JTextField jcorr;
    private javax.swing.JTextField jdir;
    private javax.swing.JTextField jeda;
    private javax.swing.JTextField jnom;
    private javax.swing.JTextField jtel;
    private javax.swing.JTextField jusu;
    private javax.swing.JTextField lcod;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

public boolean Existe(String cedula){
    
        boolean exi=false;
        ArrayList<Persona>lis=new GestionPersonas().getListPersonas();
        
        for (int i = 0; i < lis.size(); i++) {
            if(lis.get(i).getPer_cedula().equals(cedula)){
               exi=true;
               break;
            
            }  
            
        }
        
        
    
    return exi;
    }



}

